Vagrant.configure("2") do |config|
	config.vm.provider "virtualbox" do |v|
		v.memory = 512
		v.cpus = 1
	end 
	config.vm.box = "ubuntu/xenial64"
	config.vm.define "main" do |main|
		main.vm.hostname = "parktrack.net"
		main.vm.network :forwarded_port, guest: 80, host: 8080
		main.vm.network :forwarded_port, guest: 3000, host: 3000
		main.vm.provision "docker" do |d|
			d.post_install_provision "shell", path: "testEnviromentSetup/main-provision.sh"
			d.pull_images "zhajor/docker-phppgadmin"
			d.pull_images "postgres:9.5"
			d.run "postgres:9.5",
				args: "--name some-postgres -e POSTGRES_PASSWORD=secret --network=isolated_nw --ip 172.57.0.2"
			d.run "zhajor/docker-phppgadmin",
				args: "--name postg -p 3000:80 -e DB_HOST=172.57.0.2 -e DB_PORT=5432 --network=isolated_nw --ip 172.57.0.3"
			d.build_image "/vagrant/immersive-API",
				args: "-t immersiveapi"
			d.run "immersiveapi",
				args: "-p 5000:80 --network=isolated_nw --ip 172.57.0.4"
		end
	end 
end

