Vagrant.configure("2") do |config|
	config.vm.provider "virtualbox" do |v|
		v.memory = 512
		v.cpus = 1
	end 
	config.vm.box = "ubuntu/xenial64"
	config.vm.define "main" do |main|
		main.vm.hostname = "parktrack.net"
		main.vm.network :forwarded_port, guest: 80, host: 8080
		main.vm.provision "shell", path: "testEnviromentSetup/main-provision.sh"
		main.vm.provision "docker" do |d|
			d.build_image "/vagrant/immersive-API",
				args: "-t immersiveapi"
			d.run "immersiveapi",
				args: "-p 5000:80"
		end
	end 
end

